# Generated by Django 3.1.6 on 2021-02-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headline',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
