# Generated by Django 3.1.6 on 2021-02-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210217_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='publish_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
