# Generated by Django 3.1.6 on 2021-02-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_headline_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='id',
        ),
        migrations.AddField(
            model_name='headline',
            name='headline_id',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
