# Generated by Django 3.1.6 on 2021-02-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210220_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='headline_id',
        ),
        migrations.AddField(
            model_name='headline',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
