# Generated by Django 3.1.6 on 2021-02-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_headline_headline_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
