# Generated by Django 3.1.6 on 2021-02-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_headline_has_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
