# Generated by Django 3.1.6 on 2021-02-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_headline_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='headline',
            name='intern_category',
            field=models.ManyToManyField(blank=True, related_name='intern_category', to='news.InternCategory'),
        ),
    ]
