# Generated by Django 3.1.6 on 2021-02-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210222_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='intern_category',
        ),
        migrations.AddField(
            model_name='headline',
            name='intern_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='InternCategory',
        ),
    ]
